In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(12)
y = tf.constant(15)

In [3]:
z = x + y

In [4]:
z

<tf.Tensor 'add:0' shape=() dtype=int32>

In [5]:
sess = tf.Session()
sess.run(z)

27

In [6]:
a = tf.Variable(15)
b = tf.Variable(18)

c = a + b

In [7]:
c

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [9]:
sess.close()

In [10]:
init = tf.global_variables_initializer()

In [18]:
with tf.Session() as sess:
    init.run()
    print(sess.run(c))

33


# Interactive Session

In [19]:
sess = tf.InteractiveSession()

In [20]:
arr_1 = tf.constant([[13,5],[6,8]])
arr_2 = tf.constant([[12,8],[10,5]])

In [21]:
arr_1

<tf.Tensor 'Const_2:0' shape=(2, 2) dtype=int32>

In [22]:
print(arr_1)

Tensor("Const_2:0", shape=(2, 2), dtype=int32)


In [23]:
multiply = tf.matmul(arr_1,arr_2)
sess.run(multiply)

array([[206, 129],
       [152,  88]])

In [29]:
ones = tf.ones([5,5])
zeros = tf.zeros([8,2])
arr_3 = tf.linspace(2.0,20.0,10)

list_1 = [ones,zeros,arr_3,multiply]

In [30]:
for n in list_1:
    print(sess.run(n))
    print()

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]

[[206 129]
 [152  88]]

